---
- name: Install Tuxedo tools
  hosts: "*"

  tasks:
    - name: Update list of packages
      community.general.pacman:
        update_cache: true
      become: true

    - name: Install Tuxedo tools
      kewlfft.aur.aur:
        name:
          - aur/tuxedo-control-center-bin
          - aur/tuxedo-keyboard-dkms
          - aur/tuxedo-keyboard-tools
          - aur/tuxedo-touchpad-switch
          - aur/tuxedo-keyboard-ite-dkms
        use: trizen
        state: present
      become_user: aura
      become: true

    #############################################################
    # Autostart apps
    #############################################################
    - name: Create user Autostart directory
      ansible.builtin.file:
        path: ~/.config/autostart/
        state: directory
        mode: '0755'

    - name: Tuxedo Control Center (tray)
      ansible.builtin.copy:
        remote_src: true
        src: /opt/tuxedo-control-center/resources/dist/tuxedo-control-center/data/dist-data/tuxedo-control-center-tray.desktop
        dest: ~/.config/autostart/tuxedo-control-center-tray.desktop
        mode: '0755'
